@API_HostAddress = https://localhost:5050

POST {{API_HostAddress}}/products/
Content-Type: application/json

{
  "name": "Product A",
  "categories": ["c1", "c2"],
  "description": "Description Product A",
  "imageFile": "ImageProductA.jpg",
  "price": 199
}

###
