@API_HostAddress = https://localhost:5050

POST {{API_HostAddress}}/products/
Content-Type: application/json

{
  "name": "Product D",
  "categories": ["c3", "c4"],
  "description": "Description Product D",
  "imageFile": "ImageProductD.jpg",
  "price": 249
}

###

GET {{API_HostAddress}}/products/

###

GET {{API_HostAddress}}/products/018ea7d0-a10e-4738-8999-757fea86689e

###

GET {{API_HostAddress}}/products/category/c4

###

PUT {{API_HostAddress}}/products/018ea7d0-a10e-4738-8999-757fea86689e
Content-Type: application/json

{
  "name": "Product C",
  "categories": ["c1", "c4"],
  "description": "Description Product C",
  "imageFile": "ImageProductC.jpg",
  "price": 299
}

###

DELETE {{API_HostAddress}}/products/018eaacc-31e4-48d2-aa2a-b6a76b20c3a9

###